language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: zlze7nagjVns2CEQySBqLPtmrl6bVxALj0YhW0kD9tRFnP6rX5VkSAZ6/Kptpz9T7ZfBKNIXKhi1bQRy+ouDNH+j/EkldiH627NAOL+ca4NMuE8Z7rJugcfvQ5UWVsk3pEYCMqj9qZ4JTL536mP87n1kQnHuaY4egLqVSvLKKwJ9mSuqgIxuiCWoJOCkEnAtV6OsWmaK5rrJ9ZHE0zdYiwUu7sbjt3B9cLzj2Jfm2sER4tIkCVxDDLa6Vy7jqfiy8EFdcAY17TDB8BkK24SRLA1vDm1eD68ndGAEoCGsdh+VAkPPMAS8IIPFv6+9zejDMta8R86ZUBNrgeJahydxenxZ2JyRYoNAhPX8Z3wzPTHUv1TzEfJ/0zY/nS8CP2x6P7ANgiAskb3MjrQ4UFhOKoIhYgGTiM3MtSsUFiI1kl49DHIN5DrzDLbESR/KnZu0mflhGvTjaME3utnHTDkR5SroPGfU1mll1K7pPihoLrUKgF1s2VNHeG6OWQWoNtowowu8EWHoDtFmIIXTnpCYE1mb96iVGTWbag7fkbgtS8Gy5EhOAAYpmxtQt/83S8IhWXuDlQ8ounY7sbXNGo++3oK64Kev0tuOBhNonip8hnEcPWAdiIgFCBnW4QJXGhZnEfzDU9DcdYsRXoXCGW15QY7LM9m7hbwv8vnd/cGCFKk=
  app: npollock
  on:
    repo: sdossettswift/japan
